version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: ${DB_NAME}
    volumes:
      - ./etc/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432